### ISSUE TITLE
Some feedback for current design

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/csd-style#1]
1. need a toggle for sidebar TOC
2. highlights on sidebar TOC wrap text a bit nicer, especially when the toc item spans rows -- the highlight breaks across rows
3. typography can be improved? Maybe there should be two basic font styles -- consider the ones available on Google fonts since it's free? The text is slightly on the thin side to read right now. Feel free to make a more creative stance?
4. need some styling for the CalConnect "address", make it look like a mailing label, and include a link to the email and homepage url?
5. when I scroll the right side content, the left TOC should indicate the section I'm reading, e.g., an arrow at where I'm at (I remember seeing this somewhere...?)
6. maybe consider color coding the standards of different status: (https://github.com/riboseinc/csd) you can see there are 3 types of documents (governance, standard, guide), and 5 kinds of maturity (working draft, committee draft, draft standard, standard, obsolete)
7. each section should contain a link to "back to top"
8. each section title should be like github text documents (e.g., READMEs), each section title provides a link to go back to itself, so you can just "copy link" and share that link from interacting with the section title.
9. You are really free to change the layout in any creative way you want! The current header banner was just a temporary style for demo -- there's no need to keep it.
10. Color: too much purple...?

**Comment by pierrefortier** [comment]
Thanks for the feedback. Let me address it point by point:

1. Added toggle.
2. Cleaned up sidebar highlighting
3. Updated typography, let me know your thoughts
4. Updated contact info styling
5. Updated TOC to follow user's position in the page
6. Added color codes for the various document types+maturities
7. Added a general "back to top" button that sits at the bottom of the page. 
8. Added the link functionality
9-10. Tweaked the header look, as well as the general styling. 

Thanks! Please let me know of any further changes. :)

**Comment by ronaldtse** [comment]
1. Nice to have a toggle but the styling maybe improved?
2. fixed indeed.
3. The previous sans-serif font actually worked out nicer than the serif font now... But again I don't know how to make it look better.
4. Good!
5. Works!
6. In W3C standards (example: https://www.w3.org/TR/annotation-model/) , the color code of different statuses (e.g., "Recommendation", "Draft" is actually applied to the whole document. Right now it is only at the banner. Could we consider applying the status color as a hint to the document overall (e.g., the sidebar color (or a line on the sidebar)?
7. Thanks!.
8. I don't see the links? Like this:
![screen shot 2018-03-17 at 4 03 39 pm](https://user-images.githubusercontent.com/11865/37553142-cd71ee6c-29fc-11e8-84c2-a85b8ebec721.png)

9. 10. I'll leave @opoudjis to suggest improvements 😉 

11. The text lines seem to have too much vertical space to the next line, allowing very limited text to be shown in the same vertical space. The W3C sample has better readability this way.

"Standard", "Governance", "Guide" these are document types.  A document can only have one type. Each of these documents can be in a different development stage ("Working draft", "Committee draft", "Draft standard", "Standard", "Obsolete"). The current color coding does not make it clear on this?

In addition:

The W3C standards have different block styles for NOTE and EXAMPLES -- we should also do something like that. In ISO, the styles for NOTE and EXAMPLES are provided here: https://www.iso.org/sites/directives/2016/part2/index.xhtml#_idTextAnchor326.

Figure / Table styling: these may have figure/table titles and also preamble/postambles. We need to style these too.

@opoudjis can you let @pierrefortier what styles are missing? It looks like we should really have a corresponding "model element to style" mapping. Thanks!

**Comment by opoudjis** [comment]
The Montserrat header font in the document is almost worth attempt as non-bold.

The Merriweather body text font does not render at all in Safari, although that might be a matter of how web fonts get loaded. On Chrome, it looks quite spindly at the given font size, and it looks uneven in closeup—the characters are distractingly not the same height or x-height. I don't know if it's worth me arguing with Google Fonts, but Merriweather doesn't work for me.

I like the toggle and the black. I don't love the gradient on the title; I'd rather a solid on a title. And the white background inside the gradient for the consortium name is just jarring. 

Working Draft and Committee Draft colours need to be more different; you could fit a magenta in for one of them.

The orange of the WARNING up front is nice against the blue; I wouldn't mind seeing it used elsewhere in the document. Maybe even in the sidebar?

As often occurs with monospace, the monospace font is far too big compared to the body text font.

Consider making table header cells sans-serif.

The sample document given does have a lot of elements in it, but not all. These are the styles I have accounted for in CSS in the ISO template, that the CSD styling derives from:

* Footnote
* Blockquote
* Admonition (which you have: Warning)
* Sourcecode
* References
* Figure/Table Title
* Note
* Example
* Term (to be defined)
* Alternate term
* Deprecated term
* Term Definition
* Formula

**Comment by pierrefortier** [comment]
Thank you both for your comments. Here are my notes on my last updates.

I've returned to a sans-serif font for the entirety of the site, reduced line-height and tweaked around to increase readability and have more text available on screen. I also tweaked the design of the page in general, following your suggestions. 

After experimenting a little, I went with a double band to display and hierarchize the type and status of the document. Let me know what you think of this solution. 

The links next to the section titles are now auto-generated along with the TOC.

I've added styles and examples at the start of the document for:

- Footnotes
- Blockquotes
- Figure/Table title
- Notes
- Examples
- Formulas

I think that covers most of it. Please let me know your thoughts and further comments. Thanks!

**Comment by opoudjis** [comment]
Nice! I like it a lot!

Turns out that we already autogenerate ToC in the HTML, but your autogenerate may make the sidebar easier.

**Comment by ronaldtse** [comment]
Looks nice and a lot more complete!

Section title link
* can we only show the link on hover (just like GitHub's?)
* It should exist on sub-sections too

Font
* Open Sans looks to me like Helvetica or Verdana. The 200 weight of Open Sans feels better than the 400. Can we try something more "custom"?

Two issues addressed in #7, please comment there. Thanks!

**Comment by ronaldtse** [comment]
@pierrefortier 

* The double band uses quite a lot of space, is it possible to combine them? (Can we also rename "STANDARD STAGE" to "CALCONNECT STANDARD", "GOVERNANCE STAGE" to "CALCONNECT GOVERNANCE" and "GUIDE STAGE" to "CALCONNECT GUIDE"?)

* For "key words" like "MUST", "MUST NOT", etc (specified in 0.1 conventions), can we have a style that applies to them, such as bold? (@opoudjis may want to do something to annotate the output?)

I think once this feedback is addressed we're good to go!

**Comment by opoudjis** [comment]
@ronaldtse do you want bp14 as a span class, with markup like we did in asciidoctor-rfc, or do you want something more generic?

**Comment by ronaldtse** [comment]
@opoudjis maybe a marked up span is more customizable?

**Comment by opoudjis** [comment]
As agreed in that ticket: it will become `<span class="keyword">`

**Comment by pierrefortier** [comment]
Hello! Thanks for the feedback. 

- I stacked the sidebar to be more compact & changed the labels for the stages.

- I added a styling for the keywords in the css. 

- I switched the font to a lighter weight, and I think it looks quite nice!

- The links next to the titles are now there for all titles. I still need to make them appear on hover, though.

**Comment by ronaldtse** [comment]
@pierrefortier 

1. Sorry to be a bother but the header was somewhat edgy but now just too plain/static. Can we have *some* design there 😉 

2. The bibliographic references in section 2 (and in the last Bibliographic section) are too close vertically.

3. While the lighter Open Sans is a bit more readable, can we try something other than Open Sans?

Thanks!

**Comment by ronaldtse** [comment]
@pierrefortier I like it!

Last issue: seems that in #9 the paragraph spacing (and some other formatting) has changed, and there is no vertical space between paragraphs? (There is however for references 2. now)

**Comment by pierrefortier** [comment]
Fixed!
