### ISSUE TITLE
CSD styling looks strange on csd-operator-guidelines

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/csd-style#11]
I've uploaded a new HTML that is a minimal draft. There are a couple issues:

1. The title is rather long, and as a result it looks strange with such large font.
2. Terms in section 3 do not have the anchor like other subsections do. Also, anchors should only be shown on hover (like GitHub).
3. Styling for dl, ul, ol bullets are gone.
4. Bibliography section looks squished and hard to read.

**Comment by opoudjis** [comment]
Terms in the uploaded HTML are:

````
<h2 class="TermNum" id="calendar-abuse">3.3</h2>
````

so there are anchors there now; is this a CSS issue?

**Comment by ronaldtse** [comment]
@pierrefortier could you help address these issues? Thanks!

**Comment by pierrefortier** [comment]
Hi,

Yes! I've got the anchors working properly now. The other issues have also been addressed.

**Comment by ronaldtse** [comment]
@pierrefortier thanks!

Some remaining issues:

1.  The header section should have a padding that takes into account of the sidebar -- right now it is possible for the title to be partially covered by the sidebar on the left side.

<img width="937" alt="screen shot 2018-05-04 at 9 58 44 am" src="https://user-images.githubusercontent.com/11865/39610265-c4fae798-4f81-11e8-85a1-0fd2261833ba.png">

2. Somehow, some terms defined are styled differently (3.2 vs 3.3)

<img width="830" alt="screen shot 2018-05-04 at 9 43 22 am" src="https://user-images.githubusercontent.com/11865/39609996-c70184e0-4f7f-11e8-8bc6-aedd10aba7d1.png">

3. The "alternative" term should be also styled specially ("SPAM" in caps), such as in purple below the "main" term.

<img width="354" alt="screen shot 2018-05-04 at 9 43 32 am" src="https://user-images.githubusercontent.com/11865/39610013-db93c350-4f7f-11e8-9eee-16b879d09654.png">

4. The list bullets extend beyond the content box. Can we replace the "disc" `<ul><li>` bullet with a custom "dash" bullet?

<img width="583" alt="screen shot 2018-05-04 at 9 46 17 am" src="https://user-images.githubusercontent.com/11865/39610029-0302c49a-4f80-11e8-8cce-17652d5194ad.png">

```css
li {
  list-style: none;
}

li:before {
  content: "—";
}
```

Ref: https://www.w3.org/Style/Examples/007/color-bullets.en.html

**Comment by ronaldtse** [comment]
@opoudjis once these issues are fixed please help merge to asciidoctor-csd. Thanks!

**Comment by pierrefortier** [comment]
Thanks Ron, everything should be good now!

**Comment by ronaldtse** [comment]
Last thing: @pierrefortier can we also adopt the "single line" appendix title styling in CSD? i.e. "**Appendix A** (informative) **Examples**"

Thanks!

**Comment by pierrefortier** [comment]
Added!

**Comment by ronaldtse** [comment]
@pierrefortier it's all good now -- can you help merge? Thank you!

**Comment by opoudjis** [comment]
If this is merge into asciidoctor-csd, that'll have to be my job: the rendering (isodoc) component of the gem will be impacted by Pierre's design choices.
