### ISSUE TITLE
Create a paginated print CSS for CSD HTML

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/csd-style#13]
@pierrefortier could you help create a print CSS for CSD HTML? We're in a bit of a hurry. Thanks!

Ref: https://github.com/riboseinc/asciidoctor-csd/issues/26

**Comment by pierrefortier** [comment]
Hi Ron,

I uploaded a quick implementation of this. Let me know what you think! When you save as pdf, the relevant elements should be well separated into pages.

**Comment by opoudjis** [comment]
From the CSD stakeholder:

> My suggestion for how the pdf should look like are pretty simple:
> 
> I would prefer to include the toc directly in front of the foreword
> I would like the content to span over the full page
>
> All other formatting looks ok for me.

**Comment by opoudjis** [comment]
To review, tomorrow

**Comment by opoudjis** [comment]
Pierre's mods from https://github.com/riboseinc/csd-style/issues/13 do:

* Page break before each h1
* ToC at start of document, not sidebar

They do what is required, on print: `@media print`. If we implement PDF generation, I will make those overrides a separate stylesheet.

**Comment by opoudjis** [comment]
This is what it looks like; @ronaldtse, let me know if you are OK with this rendering.

[csd-operator-guidelines.pdf](https://github.com/riboseinc/csd-style/files/2053204/csd-operator-guidelines.pdf)

**Comment by ronaldtse** [comment]
@opoudjis it does look reasonable:

* It somehow looks like the header margin is 0, so the text sticks to the top? Can we set a page header margin?
* In the PDF we should also reduce the font size, text looks too large right now.

**Comment by opoudjis** [comment]
Generating the PDF via headless Chrome adresses both these issues, without having to change the stylesheet; @ronaldtse, please confirm.

[output.pdf](https://github.com/riboseinc/csd-style/files/2055674/output.pdf)

**Comment by ronaldtse** [comment]
@opoudjis Pierre actually has created some CSS for pagination -- do we not want it anymore?

**Comment by opoudjis** [comment]
We do, because this issue is going to keep coming up; my impression was that it was not required for CSD, but I may be wrong. Where is his paginating CSS?

**Comment by opoudjis** [comment]
Oh, I just saw the review request. I have already incorporated his paginating CSS into asciidoctor-csd, because I went to Pierre's branch when you asked me to look at his mods: it was before he did the pull request.
